# Generated by Django 6.0.3 on 2026-04-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(blank=True, max_length=1),
        ),
    ]
